### ISSUE TITLE
[BUG] @jvalue/jayvee-interpreter version mismatch

### ISSUE THREAD

**Issue by lukasnehrke** [jvalue/made-exercise-feedback#4]
### Description
The `setup_jayvee.sh` script installs version 0.0.17 of `@jvalue/jayvee-interpreter`, however exercises should be done using version 0.1.0, causing the exercise feedback action to fail in some cases while locally everything works fine.

### Steps to reproduce
1. Add a jayvee exercise that uses the `CSVExtractor` block type ([reference](https://github.com/lukasnehrke/made-ws2324/blob/main/exercises/exercise2.jv))
3. CI output: `Could not resolve reference to BuiltinBlocktypeDefinition named 'CSVExtractor'`

**Comment by rhazn** [comment]
Thank you very much for the report! Fixed in https://github.com/jvalue/made-exercise-feedback/commit/5a222463249ed215deafe509e1641b932c960fad
